### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'walk' (on Debian 12)

### ISSUE THREAD

**Issue by sunweaver** [tari01/LomiriForUbuntu#5]
```
Traceback (most recent call last):
  File "/home/sunweaver/MyDocuments/4debian/TEAMS/pkg-ubports/LomiriForUbuntu/./LomiriForUbuntu.py", line 123, in <module>
    cleanUp (pTempPath)
  File "/home/sunweaver/MyDocuments/4debian/TEAMS/pkg-ubports/LomiriForUbuntu/./LomiriForUbuntu.py", line 49, in cleanUp
    for sRoot, lDirs, lFiles in pTempPath.walk (top_down=False):
                                ^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'walk'
```

**Comment by tari01** [comment]
fixed via https://github.com/tari01/LomiriForUbuntu/commit/58ccac5b05ddc3e58da3a32b5d8fa611f0502d0e
